import { SavedSearch, Tender } from "@/lib/types";

export const demoSearches: SavedSearch[] = [
  {
    id: "search-1",
    userEmail: "demo@tenderhunter.dev",
    name: "Spain software and cloud delivery",
    enabled: true,
    countries: ["Spain", "France"],
    keywordsInclude: ["software", "cloud", "aws", "java", "support"],
    keywordsExclude: ["construction", "furniture", "hardware"],
    cpvInclude: ["72000000", "72262000", "72400000"],
    minValue: 50000,
    maxDaysToDeadline: 60,
    minScore: 55,
  },
  {
    id: "search-2",
    userEmail: "demo@tenderhunter.dev",
    name: "Cybersecurity and managed services",
    enabled: true,
    countries: ["Belgium", "Spain"],
    keywordsInclude: ["cyber", "security", "soc", "monitoring"],
    keywordsExclude: ["guard", "physical"],
    cpvInclude: ["72600000", "72700000"],
    minValue: 40000,
    maxDaysToDeadline: 45,
    minScore: 50,
  },
];

export const demoTenders: Tender[] = [
  {
    id: "tender-1",
    source: "ted",
    sourceNoticeId: "109312-2026",
    sourceUrl: "https://ted.europa.eu/en/notice/-/detail/109312-2026",
    title: "Cloud application support and software maintenance services",
    description: "Managed support, Java development capacity, AWS landing zone improvements, and service desk transition for a public agency.",
    buyerName: "Regional Digital Agency of Valencia",
    country: "Spain",
    region: "Valencia",
    currency: "EUR",
    estimatedValue: 320000,
    publishedAt: "2026-02-23T09:00:00.000Z",
    deadlineAt: "2026-03-24T16:00:00.000Z",
    status: "published",
    procedureType: "Open procedure",
    cpvCodes: ["72000000", "72262000", "72400000"],
  },
  {
    id: "tender-2",
    source: "ted",
    sourceNoticeId: "109261-2026",
    sourceUrl: "https://ted.europa.eu/en/notice/-/detail/109261-2026",
    title: "Cybersecurity operations centre services",
    description: "24/7 SOC monitoring, vulnerability management, incident response, and SIEM engineering support for a Belgian authority.",
    buyerName: "Brussels Mobility Authority",
    country: "Belgium",
    region: "Brussels",
    currency: "EUR",
    estimatedValue: 610000,
    publishedAt: "2026-02-16T09:00:00.000Z",
    deadlineAt: "2026-03-18T12:00:00.000Z",
    status: "published",
    procedureType: "Competitive procedure",
    cpvCodes: ["72600000", "72700000"],
  },
  {
    id: "tender-3",
    source: "ted",
    sourceNoticeId: "100204-2026",
    sourceUrl: "https://ted.europa.eu/en/notice/-/detail/100204-2026",
    title: "Furniture and storage units for municipal offices",
    description: "Supply and installation of office furniture, shelving, desks, and seating for civic administration buildings.",
    buyerName: "Municipality of Zaragoza",
    country: "Spain",
    region: "Aragon",
    currency: "EUR",
    estimatedValue: 120000,
    publishedAt: "2026-02-11T08:00:00.000Z",
    deadlineAt: "2026-03-13T10:00:00.000Z",
    status: "published",
    procedureType: "Open procedure",
    cpvCodes: ["39130000"],
  },
  // BOAMP (France) — all-threshold national notices
  {
    id: "tender-4",
    source: "boamp",
    sourceNoticeId: "26-31204",
    sourceUrl: "https://www.boamp.fr/avis/detail/26-31204",
    title: "Développement et maintenance d'applications métier en architecture cloud",
    description: "Prestation de développement logiciel, maintenance évolutive et corrective d'applications métier hébergées sur infrastructure cloud AWS/Azure, avec intégration continue et DevSecOps.",
    buyerName: "Département du Rhône — DSI",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    currency: "EUR",
    estimatedValue: 480000,
    publishedAt: "2026-02-20T08:00:00.000Z",
    deadlineAt: "2026-03-28T17:00:00.000Z",
    status: "published",
    procedureType: "APPEL_OFFRE",
    cpvCodes: ["72000000", "72262000"],
  },
  {
    id: "tender-5",
    source: "boamp",
    sourceNoticeId: "26-29847",
    sourceUrl: "https://www.boamp.fr/avis/detail/26-29847",
    title: "Services de cybersécurité et supervision SOC",
    description: "Supervision de la sécurité des SI, détection et réponse aux incidents, pentest et audit NIS2 pour une collectivité territoriale.",
    buyerName: "Métropole de Lyon — Direction du Numérique",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    currency: "EUR",
    estimatedValue: 290000,
    publishedAt: "2026-02-17T09:00:00.000Z",
    deadlineAt: "2026-03-21T16:00:00.000Z",
    status: "published",
    procedureType: "APPEL_OFFRE",
    cpvCodes: ["72600000", "72700000"],
  },
  {
    id: "tender-6",
    source: "boamp",
    sourceNoticeId: "26-27391",
    sourceUrl: "https://www.boamp.fr/avis/detail/26-27391",
    title: "AMO transformation numérique et pilotage de projets SI agiles",
    description: "Assistance à maîtrise d'ouvrage en conduite du changement, cadrage de projets de transformation numérique et pilotage agile pour une région.",
    buyerName: "Conseil Régional Occitanie",
    country: "France",
    region: "Occitanie",
    currency: "EUR",
    estimatedValue: 175000,
    publishedAt: "2026-02-10T10:00:00.000Z",
    deadlineAt: "2026-03-14T12:00:00.000Z",
    status: "published",
    procedureType: "MAPA",
    cpvCodes: ["72224000", "72222300"],
  },
  // BASE.gov.pt (Portugal) — national public contracts database
  {
    id: "tender-7",
    source: "base",
    sourceNoticeId: "3847291",
    sourceUrl: "https://www.base.gov.pt/Base4/pt/detalhe/?type=anuncio&id=3847291",
    title: "Prestação de serviços de desenvolvimento e manutenção de software — plataforma de gestão documental",
    description: "Desenvolvimento, manutenção evolutiva e suporte a plataforma de gestão documental e arquivo digital, integração com sistemas de informação municipais.",
    buyerName: "Câmara Municipal de Lisboa — Direção Municipal de Inovação",
    country: "Portugal",
    region: "Lisboa",
    currency: "EUR",
    estimatedValue: 210000,
    publishedAt: "2026-02-19T09:00:00.000Z",
    deadlineAt: "2026-03-26T17:00:00.000Z",
    status: "published",
    procedureType: "Concurso público",
    cpvCodes: ["72000000", "72212000"],
  },
  {
    id: "tender-8",
    source: "base",
    sourceNoticeId: "3841055",
    sourceUrl: "https://www.base.gov.pt/Base4/pt/detalhe/?type=anuncio&id=3841055",
    title: "Serviços de cibersegurança e auditoria de segurança de sistemas de informação",
    description: "Auditoria de segurança, testes de intrusão, análise de vulnerabilidades e acompanhamento de conformidade com o Regulamento de Segurança do Ciberespaço.",
    buyerName: "Agência para a Modernização Administrativa (AMA)",
    country: "Portugal",
    region: "Lisboa",
    currency: "EUR",
    estimatedValue: 95000,
    publishedAt: "2026-02-14T10:00:00.000Z",
    deadlineAt: "2026-03-17T16:00:00.000Z",
    status: "published",
    procedureType: "Concurso público",
    cpvCodes: ["72600000", "72246000"],
  },
  // Find a Tender (UK) — OCDS-compliant post-Brexit procurement portal
  {
    id: "tender-9",
    source: "find-a-tender",
    sourceNoticeId: "ocds-b5fd17-0048f2a1-6c93-4b7d-9f12-3a8e7cd94b21",
    sourceUrl: "https://www.find-tender.service.gov.uk/Notice/Contract/ocds-b5fd17-0048f2a1-6c93-4b7d-9f12-3a8e7cd94b21",
    title: "Cloud hosting, managed services and DevOps support for digital public services",
    description: "Provision of cloud infrastructure management, DevOps toolchain support, CI/CD pipeline engineering and 24/7 monitoring for a UK central government department.",
    buyerName: "Government Digital Service (GDS)",
    country: "United Kingdom",
    region: "London",
    currency: "GBP",
    estimatedValue: 850000,
    publishedAt: "2026-02-21T09:30:00.000Z",
    deadlineAt: "2026-03-31T23:59:00.000Z",
    status: "published",
    procedureType: "Open procedure",
    cpvCodes: ["72000000", "72400000", "72600000"],
  },
  {
    id: "tender-10",
    source: "find-a-tender",
    sourceNoticeId: "ocds-b5fd17-00a91c3d-2f84-4e6a-b311-9c7d5ef08342",
    sourceUrl: "https://www.find-tender.service.gov.uk/Notice/Contract/ocds-b5fd17-00a91c3d-2f84-4e6a-b311-9c7d5ef08342",
    title: "Agile software development and technical delivery — NHS digital transformation",
    description: "Multi-disciplinary agile delivery teams providing Java and React development, product ownership support and technical architecture for NHS digital programmes.",
    buyerName: "NHS England — Digital Transformation Directorate",
    country: "United Kingdom",
    region: "Leeds",
    currency: "GBP",
    estimatedValue: 1200000,
    publishedAt: "2026-02-18T08:00:00.000Z",
    deadlineAt: "2026-03-28T17:00:00.000Z",
    status: "published",
    procedureType: "Open procedure",
    cpvCodes: ["72262000", "72000000"],
  },
].map((tender) => ({
  lifecycleStatus: "active" as const,
  archivedAt: null,
  archiveReason: null,
  ...tender,
}));
